#!/usr/bin/env bash
# install.sh - DayShield Firewall OS installer (runs inside the live environment)
#
# This script orchestrates the full installation:
#   1. Detect or prompt for target disk
#   2. Partition the disk
#   3. Format and mount partitions
#   4. Extract the rootfs squashfs
#   5. Install and configure the bootloader
#   6. Write machine-id and enable firstboot.service
#
# Must be run as root.

set -euo pipefail

INSTALLER_DIR="/usr/lib/dayshield-installer"
TARGET_MOUNT="/mnt/target"
LOG_FILE="/tmp/dayshield-install.log"
INSTALL_HOSTNAME=""
INSTALL_ROOT_PASSWORD=""
INSTALL_WAN_IFACE=""
INSTALL_LAN_IFACE=""
INSTALL_MODE="${DAYSHIELD_INSTALL_MODE:-}"
ISO_SCAN_MOUNT=""
HAS_OSTREE_REPO=0

# Redirect output to log
exec > >(tee -a "${LOG_FILE}") 2>&1

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { echo "[INFO]  $*"; }
warn()  { echo "[WARN]  $*" >&2; }
error() { echo "[ERROR] $*" >&2; exit 1; }

require_root() {
    [[ "${EUID}" -eq 0 ]] || error "This installer must be run as root."
}

cleanup_chroot_mounts() {
    for _mount_point in run sys proc dev/pts dev; do
        umount -lf "${TARGET_MOUNT}/${_mount_point}" 2>/dev/null || true
    done
}

cleanup_all_mounts() {
    cleanup_chroot_mounts
    if [[ -n "${ISO_SCAN_MOUNT}" ]]; then
        umount -lf "${ISO_SCAN_MOUNT}" 2>/dev/null || true
        rmdir "${ISO_SCAN_MOUNT}" 2>/dev/null || true
        ISO_SCAN_MOUNT=""
    fi
    umount -lf "${TARGET_MOUNT}/boot/efi" 2>/dev/null || true
    umount -lf "${TARGET_MOUNT}/boot" 2>/dev/null || true
    umount -lf "${TARGET_MOUNT}/var" 2>/dev/null || true
    umount -lf "${TARGET_MOUNT}" 2>/dev/null || true
}

find_squashfs_image() {
    local candidate _dev _mp

    for candidate in \
        "/run/live/medium/live/filesystem.squashfs" \
        "/lib/live/mount/medium/live/filesystem.squashfs" \
        "/media/cdrom/live/filesystem.squashfs" \
        "/media/live/live/filesystem.squashfs" \
        "/run/initramfs/live/live/filesystem.squashfs"
    do
        if [[ -f "${candidate}" ]]; then
            printf '%s\n' "${candidate}"
            return 0
        fi
    done

    # Last resort: scan block devices for DAYSHIELD media label.
    _dev="$(blkid -t LABEL=DAYSHIELD -o device 2>/dev/null | head -n1 || true)"
    if [[ -n "${_dev}" ]]; then
        _mp="$(mktemp -d)"
        if mount -o ro "${_dev}" "${_mp}" 2>/dev/null; then
            if [[ -f "${_mp}/live/filesystem.squashfs" ]]; then
                ISO_SCAN_MOUNT="${_mp}"
                printf '%s\n' "${_mp}/live/filesystem.squashfs"
                return 0
            fi
            umount "${_mp}" 2>/dev/null || true
        fi
        rmdir "${_mp}" 2>/dev/null || true
    fi

    return 1
}

configure_ssh_access() {
    local sshd_config="${TARGET_MOUNT}/etc/ssh/sshd_config"
    local sshd_dropin_dir="${TARGET_MOUNT}/etc/ssh/sshd_config.d"
    local sshd_dropin="${sshd_dropin_dir}/10-dayshield-root-login.conf"

    info "Configuring SSH to allow root password login …"
    mkdir -p "${sshd_dropin_dir}"
    cat > "${sshd_dropin}" <<'EOF'
# Generated by the DayShield installer.
PermitRootLogin yes
PasswordAuthentication yes
EOF

    if [[ -f "${sshd_config}" ]] && \
       ! grep -qE '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/\*\.conf([[:space:]]|$)' "${sshd_config}"; then
        local sshd_config_tmp
        sshd_config_tmp="$(mktemp)"
        {
            printf '%s\n' 'Include /etc/ssh/sshd_config.d/*.conf'
            cat "${sshd_config}"
        } > "${sshd_config_tmp}"
        cat "${sshd_config_tmp}" > "${sshd_config}"
        rm -f "${sshd_config_tmp}"
    fi
}
device_base_name() {
    local dev="$1"
    local base re
    base="$(basename "${dev}")"
    if [[ "${base}" =~ ^nvme[0-9]+n[0-9]+$ ]]; then
        :
    elif [[ "${base}" =~ ^mmcblk[0-9]+$ ]]; then
        :
    elif [[ "${base}" =~ ^(nvme[0-9]+n[0-9]+)p[0-9]+$ ]]; then
        re="${BASH_REMATCH[1]}"
        base="${re}"
    elif [[ "${base}" =~ ^(mmcblk[0-9]+)p[0-9]+$ ]]; then
        re="${BASH_REMATCH[1]}"
        base="${re}"
    else
        base="${base%%[0-9]*}"
    fi
    printf '%s\n' "${base}"
}

live_medium_base_disk() {
    local mounted
    mounted="$(lsblk -n -o NAME,MOUNTPOINT \
        | awk '$2=="/run/live/medium" || $2=="/media/cdrom" {print $1}' \
        | head -n1 || true)"
    if [[ -z "${mounted}" ]]; then
        return 0
    fi
    device_base_name "/dev/${mounted}"
}

validate_target_disk() {
    local target="$1"
    local target_base live_base
    target_base="$(device_base_name "${target}")"
    live_base="$(live_medium_base_disk || true)"
    if [[ -n "${live_base}" ]] && [[ "${target_base}" == "${live_base}" ]]; then
        error "Refusing to install onto live media disk (${target})."
    fi
}

valid_hostname() {
    local hostname="$1"
    [[ "${hostname}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]
}

valid_iface_name() {
    local iface="$1"
    [[ "${iface}" =~ ^[[:alnum:]_.:-]+$ ]]
}

valid_ipv4_cidr() {
    local cidr="$1"
    local ip prefix octet
    local -a octets

    [[ "${cidr}" == */* ]] || return 1

    ip="${cidr%/*}"
    prefix="${cidr#*/}"
    [[ "${ip}" != "${cidr}" ]] || return 1
    [[ "${prefix}" =~ ^([0-9]|[12][0-9]|3[0-2])$ ]] || return 1

    IFS='.' read -r -a octets <<< "${ip}"
    [[ ${#octets[@]} -eq 4 ]] || return 1
    for octet in "${octets[@]}"; do
        [[ "${octet}" =~ ^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]] || return 1
    done
}

valid_ipv4() {
    local ip="$1" octet
    local -a octets

    IFS='.' read -r -a octets <<< "${ip}"
    [[ ${#octets[@]} -eq 4 ]] || return 1
    for octet in "${octets[@]}"; do
        [[ "${octet}" =~ ^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]] || return 1
    done
}

ipv4_to_int() {
    local ip="$1"
    local -a octets
    IFS='.' read -r -a octets <<< "${ip}"
    printf '%u\n' "$(( (octets[0] << 24) | (octets[1] << 16) | (octets[2] << 8) | octets[3] ))"
}

int_to_ipv4() {
    local value="$1"
    printf '%d.%d.%d.%d\n' \
        "$(( (value >> 24) & 255 ))" \
        "$(( (value >> 16) & 255 ))" \
        "$(( (value >> 8) & 255 ))" \
        "$(( value & 255 ))"
}

calculate_lan_dhcp_pool() {
    local cidr="$1"
    local ip prefix ip_int mask network broadcast first_host last_host start end

    ip="${cidr%/*}"
    prefix="${cidr#*/}"
    ip_int="$(ipv4_to_int "${ip}")"

    if (( prefix == 32 )); then
        mask=4294967295
    else
        mask=$(( (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF ))
    fi

    network=$(( ip_int & mask ))
    broadcast=$(( network | ((~mask) & 0xFFFFFFFF) ))

    if (( prefix >= 31 )); then
        first_host="${network}"
        last_host="${broadcast}"
    else
        first_host=$(( network + 1 ))
        last_host=$(( broadcast - 1 ))
    fi

    # Prefer a .100-.199 style range where subnet size permits it.
    start=$(( network + 100 ))
    end=$(( network + 199 ))

    if (( start < first_host || start > last_host )); then
        start="${first_host}"
    fi
    if (( end > last_host )); then
        end="${last_host}"
    fi
    if (( end < start )); then
        end="${start}"
    fi

    printf '%s %s\n' "$(int_to_ipv4 "${start}")" "$(int_to_ipv4 "${end}")"
}

validate_lan_runtime_config() {
    local lan_int start_int end_int mask network start_network end_network

    LAN_CIDR="${DAYSHIELD_LAN_CIDR:-192.168.1.1/24}"
    valid_ipv4_cidr "${LAN_CIDR}" || \
        error "Invalid LAN CIDR '${LAN_CIDR}'. Use IPv4 CIDR format like 192.168.1.1/24."

    LAN_IP="${LAN_CIDR%/*}"
    LAN_PREFIX="${LAN_CIDR#*/}"

    if [[ -n "${DAYSHIELD_LAN_DHCP_START:-}" || -n "${DAYSHIELD_LAN_DHCP_END:-}" ]]; then
        [[ -n "${DAYSHIELD_LAN_DHCP_START:-}" && -n "${DAYSHIELD_LAN_DHCP_END:-}" ]] || \
            error "Set both DAYSHIELD_LAN_DHCP_START and DAYSHIELD_LAN_DHCP_END, or neither."
        valid_ipv4 "${DAYSHIELD_LAN_DHCP_START}" || \
            error "Invalid DHCP start address '${DAYSHIELD_LAN_DHCP_START}'."
        valid_ipv4 "${DAYSHIELD_LAN_DHCP_END}" || \
            error "Invalid DHCP end address '${DAYSHIELD_LAN_DHCP_END}'."
        LAN_DHCP_START="${DAYSHIELD_LAN_DHCP_START}"
        LAN_DHCP_END="${DAYSHIELD_LAN_DHCP_END}"
    else
        read -r LAN_DHCP_START LAN_DHCP_END <<< "$(calculate_lan_dhcp_pool "${LAN_CIDR}")"
    fi

    lan_int="$(ipv4_to_int "${LAN_IP}")"
    start_int="$(ipv4_to_int "${LAN_DHCP_START}")"
    end_int="$(ipv4_to_int "${LAN_DHCP_END}")"

    (( start_int <= end_int )) || \
        error "Invalid DHCP range: ${LAN_DHCP_START} must be less than or equal to ${LAN_DHCP_END}."

    if (( LAN_PREFIX == 32 )); then
        mask=4294967295
    else
        mask=$(( (0xFFFFFFFF << (32 - LAN_PREFIX)) & 0xFFFFFFFF ))
    fi

    network=$(( lan_int & mask ))
    start_network=$(( start_int & mask ))
    end_network=$(( end_int & mask ))

    (( start_network == network && end_network == network )) || \
        error "DHCP range ${LAN_DHCP_START}-${LAN_DHCP_END} must be inside LAN subnet ${LAN_CIDR}."
    (( lan_int < start_int || lan_int > end_int )) || \
        error "DHCP range must not include the LAN gateway address ${LAN_IP}."
}

bootstrap_state_partition() {
    local state_part="$1" state_mount

    state_mount="$(mktemp -d)"
    mount "${state_part}" "${state_mount}"

    if [[ -d "${TARGET_MOUNT}/var" ]]; then
        info "Bootstrapping persistent /var state partition ..."
        if command -v rsync >/dev/null 2>&1; then
            rsync -aHAX --numeric-ids "${TARGET_MOUNT}/var/" "${state_mount}/"
        else
            tar -C "${TARGET_MOUNT}/var" -cpf - . | tar -C "${state_mount}" -xpf -
        fi
    fi

    mkdir -p "${state_mount}/lib/dayshield"
    umount "${state_mount}"
    rmdir "${state_mount}"
}

require_ostree_tooling() {
    local target="$1"
    local missing=0

    if [[ ! -x "${target}/usr/bin/ostree" ]]; then
        warn "Installed target is missing /usr/bin/ostree."
        missing=1
    fi
    if [[ ! -x "${target}/usr/local/lib/dayshield/ostree-update.sh" ]]; then
        warn "Installed target is missing /usr/local/lib/dayshield/ostree-update.sh."
        missing=1
    fi

    if (( missing )); then
        error "Input rootfs is missing required DayShield OSTree update tooling; rebuild dayshield-rootfs and recreate the ISO."
    fi
}

stage_ostree_seed_if_present() {
    local target="$1"
    local osname ref

    [[ -d "${target}/ostree/repo" ]] || return 0

    if ! command -v ostree >/dev/null 2>&1; then
        warn "ostree CLI is unavailable in live environment; skipping OSTree deployment staging."
        return 0
    fi

    osname="${DAYSHIELD_OSTREE_OSNAME:-dayshield}"
    ref="${DAYSHIELD_OSTREE_REF:-}"
    if [[ -z "${ref}" ]]; then
        ref="$(ostree --repo="${target}/ostree/repo" refs --list 2>/dev/null | head -n1 || true)"
    fi

    if [[ -z "${ref}" ]]; then
        if [[ -f "${target}/usr/local/share/dayshield-updates/ostree-build-manifest.json" ]]; then
            error "OSTree repo present but no refs discovered in ${target}/ostree/repo; rootfs image does not contain a valid OSTree repo."
        fi
        warn "OSTree repo present but no refs discovered; skipping deployment staging."
        return 0
    fi

    info "Staging OSTree deployment '${ref}' for stateroot '${osname}' ..."
    if ! ostree admin --sysroot="${target}" os-init "${osname}" 2>/dev/null; then
        info "OSTree stateroot '${osname}' already initialized."
    fi
    ostree admin --sysroot="${target}" deploy --os="${osname}" "${ref}"
}

SQUASHFS_IMG="$(find_squashfs_image || true)"
if [[ -z "${SQUASHFS_IMG}" ]] || [[ ! -f "${SQUASHFS_IMG}" ]]; then
    error "Cannot locate filesystem.squashfs on the live medium. Checked live-boot/dracut paths and DAYSHIELD-labeled media."
fi

valid_root_password() {
    local password="$1"
    [[ "${password}" != *:* ]] || return 1
    [[ ! "${password}" =~ [[:cntrl:]] ]] || return 1
    return 0
}

collect_install_configuration() {
    local unattended="${DAYSHIELD_UNATTENDED:-0}"
    local _wan_idx _lan_idx

    # Hostname
    INSTALL_HOSTNAME="${DAYSHIELD_HOSTNAME:-}"
    if [[ -z "${INSTALL_HOSTNAME}" ]]; then
        if [[ "${unattended}" == "1" ]]; then
            INSTALL_HOSTNAME="dayshield"
        else
            read -rp "Hostname [dayshield]: " INSTALL_HOSTNAME
            INSTALL_HOSTNAME="${INSTALL_HOSTNAME:-dayshield}"
        fi
    fi
    valid_hostname "${INSTALL_HOSTNAME}" || \
        error "Invalid hostname '${INSTALL_HOSTNAME}'. Use letters, digits, and '-' only."

    # Root password
    INSTALL_ROOT_PASSWORD="${DAYSHIELD_ROOT_PASSWORD:-}"
    if [[ -z "${INSTALL_ROOT_PASSWORD}" ]]; then
        if [[ "${unattended}" == "1" ]]; then
            error "DAYSHIELD_ROOT_PASSWORD is required when DAYSHIELD_UNATTENDED=1."
        fi

        local pass1="" pass2=""
        while true; do
            read -rsp "Set root password: " pass1
            echo ""
            read -rsp "Confirm root password: " pass2
            echo ""
            [[ -n "${pass1}" ]] || { warn "Password cannot be empty."; continue; }
            [[ "${pass1}" == "${pass2}" ]] || { warn "Passwords do not match."; continue; }
            valid_root_password "${pass1}" || {
                warn "Password cannot contain ':' or control characters."
                continue
            }
            INSTALL_ROOT_PASSWORD="${pass1}"
            break
        done
    else
        valid_root_password "${INSTALL_ROOT_PASSWORD}" || \
            error "Invalid root password from DAYSHIELD_ROOT_PASSWORD. Avoid ':' and control characters."
    fi

    # Interface selection
    mapfile -t _ifaces < <(find /sys/class/net -mindepth 1 -maxdepth 1 -printf '%f\n' | grep -v '^lo$' | sort)
    [[ ${#_ifaces[@]} -ge 2 ]] || error "At least two non-loopback network interfaces are required."

    INSTALL_WAN_IFACE="${DAYSHIELD_WAN_IFACE:-}"
    INSTALL_LAN_IFACE="${DAYSHIELD_LAN_IFACE:-}"

    if [[ -z "${INSTALL_WAN_IFACE}" ]]; then
        if [[ "${unattended}" == "1" ]]; then
            INSTALL_WAN_IFACE="${_ifaces[0]}"
        else
            echo ""
            echo "Available network interfaces:"
            for i in "${!_ifaces[@]}"; do
                echo "  [$i] ${_ifaces[$i]}"
            done
            read -rp "Select WAN interface [0]: " _wan_idx
            _wan_idx="${_wan_idx:-0}"
            [[ "${_wan_idx}" =~ ^[0-9]+$ ]] || error "Invalid WAN interface index: ${_wan_idx}"
            [[ "${_wan_idx}" -lt "${#_ifaces[@]}" ]] || error "WAN interface index out of range: ${_wan_idx}"
            INSTALL_WAN_IFACE="${_ifaces[${_wan_idx}]}"
        fi
    fi

    if [[ -z "${INSTALL_LAN_IFACE}" ]]; then
        if [[ "${unattended}" == "1" ]]; then
            INSTALL_LAN_IFACE="${_ifaces[1]}"
        else
            read -rp "Select LAN interface [1]: " _lan_idx
            _lan_idx="${_lan_idx:-1}"
            [[ "${_lan_idx}" =~ ^[0-9]+$ ]] || error "Invalid LAN interface index: ${_lan_idx}"
            [[ "${_lan_idx}" -lt "${#_ifaces[@]}" ]] || error "LAN interface index out of range: ${_lan_idx}"
            INSTALL_LAN_IFACE="${_ifaces[${_lan_idx}]}"
        fi
    fi

    valid_iface_name "${INSTALL_WAN_IFACE}" || error "Invalid WAN interface name: ${INSTALL_WAN_IFACE}"
    valid_iface_name "${INSTALL_LAN_IFACE}" || error "Invalid LAN interface name: ${INSTALL_LAN_IFACE}"
    [[ "${INSTALL_WAN_IFACE}" != "${INSTALL_LAN_IFACE}" ]] || error "WAN and LAN interfaces must be different."
}
detect_target_disk() {
    # Look for block devices that are not the live medium
    local disks
    disks="$(lsblk -d -n -o NAME,TYPE,RM \
             | awk '$2=="disk" && $3=="0" {print "/dev/" $1}')"

    # Exclude the current boot device (the ISO)
    local boot_source
    local boot_dev
    local boot_pkname
    boot_source="$(findmnt -n -o SOURCE /run/live/medium 2>/dev/null || \
                   findmnt -n -o SOURCE /media/cdrom 2>/dev/null || true)"
    boot_dev=""
    if [[ -n "${boot_source}" ]] && [[ "${boot_source}" == /dev/* ]]; then
        boot_pkname="$(lsblk -ndo PKNAME "${boot_source}" 2>/dev/null || true)"
        if [[ -n "${boot_pkname}" ]]; then
            boot_dev="/dev/${boot_pkname}"
        else
            boot_dev="${boot_source}"
        fi
    fi

    local candidates=()
    while IFS= read -r dev; do
        [[ -n "${boot_dev}" ]] && [[ "${dev}" == "${boot_dev}" ]] && continue
        candidates+=("${dev}")
    done <<< "${disks}"

    if [[ ${#candidates[@]} -eq 0 ]]; then
        error "No suitable target disk detected."
    fi

    if [[ ${#candidates[@]} -eq 1 ]]; then
        TARGET_DISK="${candidates[0]}"
        info "Target disk auto-detected: ${TARGET_DISK}"
    else
        echo ""
        echo "Available disks:"
        for i in "${!candidates[@]}"; do
            SIZE="$(lsblk -d -n -o SIZE "${candidates[$i]}" 2>/dev/null || echo '?')"
            echo "  [$i] ${candidates[$i]}  ${SIZE}"
        done
        read -rp "Select disk [0]: " sel
        sel="${sel:-0}"
        [[ "${sel}" =~ ^[0-9]+$ ]] || error "Invalid disk selection: ${sel}"
        (( sel < ${#candidates[@]} )) || error "Disk selection out of range: ${sel}"
        TARGET_DISK="${candidates[sel]}"
        info "Selected target disk: ${TARGET_DISK}"
    fi
}

choose_install_mode() {
    if [[ -n "${INSTALL_MODE}" ]]; then
        case "${INSTALL_MODE}" in
            upgrade|reinstall|install) ;;
            *) error "Invalid DAYSHIELD_INSTALL_MODE='${INSTALL_MODE}'. Use upgrade or reinstall." ;;
        esac
        [[ "${INSTALL_MODE}" == "install" ]] && INSTALL_MODE="reinstall"
        return 0
    fi

    if [[ "${DAYSHIELD_UNATTENDED:-}" == "1" ]]; then
        INSTALL_MODE="reinstall"
        return 0
    fi

    echo ""
    echo "DayShield ISO options:"
    echo "  [1] Upgrade from ISO   - stage this ISO OSTree deployment on an existing DayShield install"
    echo "  [2] Reinstall from ISO - erase the selected disk and install fresh"
    while true; do
        read -rp "Select mode [1-2]: " _mode
        _mode="${_mode:-1}"
        case "${_mode}" in
            1|upgrade|Upgrade)
                INSTALL_MODE="upgrade"
                return 0
                ;;
            2|reinstall|Reinstall|install|Install)
                INSTALL_MODE="reinstall"
                return 0
                ;;
            *)
                warn "Please enter 1 or 2."
                ;;
        esac
    done
}

# ---------------------------------------------------------------------------
# Main installation flow
# ---------------------------------------------------------------------------
require_root
trap cleanup_all_mounts EXIT

TARGET_DISK="${DAYSHIELD_TARGET_DISK:-}"

if [[ -z "${TARGET_DISK}" ]]; then
    detect_target_disk
fi

[[ -b "${TARGET_DISK}" ]] || error "Not a block device: ${TARGET_DISK}"
validate_target_disk "${TARGET_DISK}"

choose_install_mode

if [[ "${INSTALL_MODE}" == "upgrade" ]]; then
    info "Upgrading existing DayShield appliance on ${TARGET_DISK} from ISO"
    info "An OSTree deployment from this ISO will be staged for the next boot."
    if [[ "${DAYSHIELD_UNATTENDED:-}" != "1" ]]; then
        read -rp "Type '${TARGET_DISK}' to stage ISO upgrade: " confirm
        [[ "${confirm}" == "${TARGET_DISK}" ]] || error "Upgrade cancelled."
    fi
    "${INSTALLER_DIR}/upgrade-rootfs.sh" "${TARGET_DISK}" "${SQUASHFS_IMG}"
    cleanup_all_mounts
    trap - EXIT
    info "Upgrade staged. Remove the installation medium and reboot."
    exit 0
fi

info "Reinstalling DayShield Firewall OS to ${TARGET_DISK}"
info "WARNING: All data on ${TARGET_DISK} will be erased."

# Confirm unless DAYSHIELD_UNATTENDED=1
if [[ "${DAYSHIELD_UNATTENDED:-}" != "1" ]]; then
    read -rp "Type '${TARGET_DISK}' to continue: " confirm
    [[ "${confirm}" == "${TARGET_DISK}" ]] || error "Installation cancelled."
fi

collect_install_configuration
validate_lan_runtime_config
info "Install configuration:"
info "  hostname : ${INSTALL_HOSTNAME}"
info "  WAN iface: ${INSTALL_WAN_IFACE}"
info "  LAN iface: ${INSTALL_LAN_IFACE}"
info "  LAN CIDR : ${LAN_CIDR}"

# ---------------------------------------------------------------------------
# Partition
# ---------------------------------------------------------------------------
info "Partitioning ${TARGET_DISK} …"
"${INSTALLER_DIR}/partition.sh" "${TARGET_DISK}"

# Determine partition names (handle nvme, mmcblk naming conventions)
if [[ "${TARGET_DISK}" =~ (nvme|mmcblk) ]]; then
    EFI_PART="${TARGET_DISK}p2"
    BOOT_PART="${TARGET_DISK}p3"
    SYSROOT_PART="${TARGET_DISK}p4"
    STATE_PART="${TARGET_DISK}p5"
else
    EFI_PART="${TARGET_DISK}2"
    BOOT_PART="${TARGET_DISK}3"
    SYSROOT_PART="${TARGET_DISK}4"
    STATE_PART="${TARGET_DISK}5"
fi

# ---------------------------------------------------------------------------
# Format
# ---------------------------------------------------------------------------
[[ -b "${EFI_PART}" ]]  || error "EFI partition device not found: ${EFI_PART}"
[[ -b "${BOOT_PART}" ]] || error "Boot partition device not found: ${BOOT_PART}"
[[ -b "${SYSROOT_PART}" ]] || error "Sysroot partition device not found: ${SYSROOT_PART}"
[[ -b "${STATE_PART}" ]] || error "State partition device not found: ${STATE_PART}"

info "Formatting EFI partition: ${EFI_PART}"
mkfs.fat -F 32 -n "DS_EFI" "${EFI_PART}"

info "Formatting shared boot partition: ${BOOT_PART}"
mkfs.ext4 -F -L "DAYSHIELD_BOOT" "${BOOT_PART}"

info "Formatting OSTree sysroot partition: ${SYSROOT_PART}"
mkfs.ext4 -F -L "DS_SYSROOT" "${SYSROOT_PART}"

info "Formatting persistent state partition: ${STATE_PART}"
mkfs.ext4 -F -L "DS_STATE" "${STATE_PART}"

# ---------------------------------------------------------------------------
# Mount
# ---------------------------------------------------------------------------
mkdir -p "${TARGET_MOUNT}"
mount "${SYSROOT_PART}" "${TARGET_MOUNT}"
mkdir -p "${TARGET_MOUNT}/boot"
mount "${BOOT_PART}" "${TARGET_MOUNT}/boot"
mkdir -p "${TARGET_MOUNT}/boot/efi"
mount "${EFI_PART}" "${TARGET_MOUNT}/boot/efi"

# ---------------------------------------------------------------------------
# Extract rootfs
# ---------------------------------------------------------------------------
info "Extracting rootfs squashfs …"
"${INSTALLER_DIR}/copy-rootfs.sh" "${SQUASHFS_IMG}" "${TARGET_MOUNT}"
require_ostree_tooling "${TARGET_MOUNT}"
bootstrap_state_partition "${STATE_PART}"
mount "${STATE_PART}" "${TARGET_MOUNT}/var"
if [[ -d "${TARGET_MOUNT}/ostree/repo" ]]; then
    HAS_OSTREE_REPO=1
fi

# ---------------------------------------------------------------------------
# Clean live-boot artefacts from the installed target
# ---------------------------------------------------------------------------
info "Preparing target chroot environment …"
for _fs in dev dev/pts proc sys run; do
    mkdir -p "${TARGET_MOUNT}/${_fs}"
    mount --bind "/${_fs}" "${TARGET_MOUNT}/${_fs}"
done

if (( HAS_OSTREE_REPO )); then
    stage_ostree_seed_if_present "${TARGET_MOUNT}"
else
    info "Purging live-boot / live-config packages from target …"
    chroot "${TARGET_MOUNT}" /bin/sh -c 'dpkg --configure -a 2>/dev/null || true'
    chroot "${TARGET_MOUNT}" /bin/sh -c \
        'DEBIAN_FRONTEND=noninteractive apt-get -y --purge remove \
            live-boot live-boot-initramfs-tools \
            live-config live-config-systemd live-config-sysvinit \
            live-tools 2>/dev/null || true'

    # Remove any leftover live directories not caught by the package purge
    info "Removing leftover live directories …"
    rm -rf \
        "${TARGET_MOUNT}/lib/live" \
        "${TARGET_MOUNT}/usr/lib/live" \
        "${TARGET_MOUNT}/etc/live"

    # Regenerate a clean initramfs without live-boot hooks
    info "Regenerating initramfs inside target …"
    chroot "${TARGET_MOUNT}" update-initramfs -u -k all
fi

FINALIZE_SCRIPT="${TARGET_MOUNT}/usr/local/lib/dayshield/installer-finalize.sh"
if [[ -x "${FINALIZE_SCRIPT}" ]]; then
    info "Applying runtime configuration contracts via installer finalization helper …"
    "${FINALIZE_SCRIPT}" \
        "${TARGET_MOUNT}" \
        "${INSTALL_HOSTNAME}" \
        "${INSTALL_ROOT_PASSWORD}" \
        "${INSTALL_WAN_IFACE}" \
        "dhcp" \
        "" \
        "" \
        "${INSTALL_LAN_IFACE}" \
        "${LAN_IP}" \
        "${LAN_PREFIX}" \
        "${LAN_DHCP_START}" \
        "${LAN_DHCP_END}"
else
    warn "Installer finalization helper not found in target rootfs: ${FINALIZE_SCRIPT}"
fi
unset INSTALL_ROOT_PASSWORD

cleanup_chroot_mounts

# ---------------------------------------------------------------------------
# Configure target system
# ---------------------------------------------------------------------------

configure_ssh_access

# Write a fresh machine-id (will be fully regenerated on first boot by systemd)
info "Writing machine-id …"
truncate -s 0 "${TARGET_MOUNT}/etc/machine-id"

# Write fstab
info "Writing /etc/fstab …"
ROOT_UUID="$(blkid -s UUID -o value "${SYSROOT_PART}")"
BOOT_UUID="$(blkid -s UUID -o value "${BOOT_PART}")"
EFI_UUID="$(blkid -s UUID -o value "${EFI_PART}")"
STATE_UUID="$(blkid -s UUID -o value "${STATE_PART}")"
ROOT_MOUNT_OPTS="defaults,noatime"
if (( HAS_OSTREE_REPO )); then
    ROOT_MOUNT_OPTS="${ROOT_MOUNT_OPTS},ro"
fi
cat > "${TARGET_MOUNT}/etc/fstab" <<EOF
# /etc/fstab - generated by DayShield installer
UUID=${ROOT_UUID}  /          ext4  ${ROOT_MOUNT_OPTS}  0  1
UUID=${BOOT_UUID}  /boot      ext4  defaults,noatime  0  2
UUID=${EFI_UUID}   /boot/efi  vfat  umask=0077        0  2
UUID=${STATE_UUID} /var       ext4  defaults,noatime  0  2
tmpfs              /tmp       tmpfs defaults           0  0
EOF

# ---------------------------------------------------------------------------
# Enable systemd-networkd on the target by creating the
# required symlinks directly.  Pseudo-filesystem bind mounts were torn down
# above (after update-initramfs), so chroot + systemctl is not available at
# this point.
SYSTEMD_DIR="${TARGET_MOUNT}/etc/systemd/system"
mkdir -p \
    "${SYSTEMD_DIR}/multi-user.target.wants" \
    "${SYSTEMD_DIR}/sockets.target.wants" \
    "${SYSTEMD_DIR}/network-online.target.wants"
for _unit_dir in /lib/systemd/system /usr/lib/systemd/system; do
    if [[ -f "${TARGET_MOUNT}${_unit_dir}/systemd-networkd.service" ]]; then
        ln -sf "${_unit_dir}/systemd-networkd.service" \
            "${SYSTEMD_DIR}/multi-user.target.wants/systemd-networkd.service" || true
        ln -sf "${_unit_dir}/systemd-networkd.socket" \
            "${SYSTEMD_DIR}/sockets.target.wants/systemd-networkd.socket" || true
        ln -sf "${_unit_dir}/systemd-networkd-wait-online.service" \
            "${SYSTEMD_DIR}/network-online.target.wants/systemd-networkd-wait-online.service" || true
        break
    fi
done

# Mask systemd-resolved; the installed system uses unbound (port 53) as its
# DNS resolver.  Enabling both would cause a port-53 conflict on first boot.
ln -sf /dev/null "${SYSTEMD_DIR}/systemd-resolved.service" 2>/dev/null || true
# unbound-resolvconf expects /sbin/resolvconf, which DayShield does not ship.
ln -sf /dev/null "${SYSTEMD_DIR}/unbound-resolvconf.service" 2>/dev/null || true

# Point resolv.conf at 127.0.0.1 (unbound listening on all interfaces).
# systemd-resolved is masked above so its stub resolver at
# /run/systemd/resolve/resolv.conf is never populated; a plain file is safer.
rm -f "${TARGET_MOUNT}/etc/resolv.conf"
printf 'nameserver 127.0.0.1\n' > "${TARGET_MOUNT}/etc/resolv.conf"

# ---------------------------------------------------------------------------
# Firstboot marker
# ---------------------------------------------------------------------------
info "Creating firstboot marker …"
mkdir -p "${TARGET_MOUNT}/etc/dayshield"
touch "${TARGET_MOUNT}/etc/dayshield/.firstboot"

# ---------------------------------------------------------------------------
# Bootloader
# ---------------------------------------------------------------------------
info "Installing bootloader …"
"${INSTALLER_DIR}/configure-bootloader.sh" "${TARGET_DISK}" "${TARGET_MOUNT}"

# ---------------------------------------------------------------------------
# Enable firstboot.service
# ---------------------------------------------------------------------------
info "Enabling firstboot.service …"
SYSTEMD_DIR="${TARGET_MOUNT}/etc/systemd/system"
mkdir -p "${SYSTEMD_DIR}/multi-user.target.wants"
install -m 644 "${INSTALLER_DIR}/firstboot.service" \
    "${SYSTEMD_DIR}/firstboot.service"
ln -sf "/etc/systemd/system/firstboot.service" \
    "${SYSTEMD_DIR}/multi-user.target.wants/firstboot.service"

# ---------------------------------------------------------------------------
# Unmount
# ---------------------------------------------------------------------------
info "Syncing filesystems …"
sync
info "Unmounting target …"
umount -R "${TARGET_MOUNT}"
trap - EXIT

info "Installation complete. Remove the installation medium and reboot."
