name: ShellCheck

on:
  push:
    paths:
      - 'scripts/**'
      - 'config/installer/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'config/installer/**'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
        with:
          files: |
            Makefile
            scripts/*.sh
            config/installer/*.sh
